In [24]:
import os
import numpy as np

In [80]:
#All put together
water=os.path.join('data', 'water.xyz')
distance= numpy.genfromtxt(fname=water, skip_header=2, dtype='unicode')
molecule=distance[:,1:]
molecule= molecule.astype(numpy.float)
mol=distance[:,0]
atoms=len(mol)
for start in range(0,atoms):
    for end in range(0,atoms):
        #Eliminates Duplicates
        if start<end:
            xdist=molecule[start,0]-molecule[end,0]
            ydist=molecule[start,1]-molecule[end,1]
            zdist=molecule[start,2]-molecule[end,2]
            bondlength=numpy.sqrt(xdist**2+ydist**2+zdist**2)
            #Eliminates distances outside min/max bond length
            if bondlength >0 and bondlength <= 1.5:
                print(F'{mol[start]} to {mol[end]} : {bondlength:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [85]:
# Same Process, but prints the output into a new file
filehandle= open('bonds.txt', 'w+')
water=os.path.join('data', 'water.xyz')
distance= numpy.genfromtxt(fname=water, skip_header=2, dtype='unicode')
molecule=distance[:,1:]
molecule= molecule.astype(numpy.float)
mol=distance[:,0]
atoms=len(mol)
for start in range(0,atoms):
    for end in range(0,atoms):
        #Eliminates Duplicates
        if start<end:
            xdist=molecule[start,0]-molecule[end,0]
            ydist=molecule[start,1]-molecule[end,1]
            zdist=molecule[start,2]-molecule[end,2]
            bondlength=numpy.sqrt(xdist**2+ydist**2+zdist**2)
            #Eliminates distances outside min/max bond length
            if bondlength >0 and bondlength <= 1.5:
                filehandle.write(F'{mol[start]} to {mol[end]} \t {bondlength:.3f}\n')
    
filehandle.close()

In [44]:
#Get to Data and make numpy array
water=os.path.join('data', 'water.xyz')
distance= numpy.genfromtxt(fname=water, skip_header=2, dtype='unicode')
print(distance)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [62]:
#Simplify array to just have molecule coordinates
molecule=distance[:,1:]
molecule= molecule.astype(numpy.float)
print(molecule)



[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [59]:
mol=distance[:,0]
atoms=len(mol)
print(mol)
print(atoms)


['O' 'H1' 'H2']
3


In [67]:
for start in range(0,atoms):
    for end in range(0,atoms):
        xdist=molecule[start,0]-molecule[end,0]
        ydist=molecule[start,1]-molecule[end,1]
        zdist=molecule[start,2]-molecule[end,2]
        print(F'{mol[start]} to {mol[end]} : {xdist}')



O to O : 0.0
O to H1 : 0.0
O to H2 : 0.0
H1 to O : -0.0
H1 to H1 : 0.0
H1 to H2 : -0.0
H2 to O : 0.0
H2 to H1 : 0.0
H2 to H2 : 0.0
