## BigChungus

In [2]:
import numpy
import os

In [3]:
wherestheleakmaam=os.path.join('data','water.xyz')
print(wherestheleakmaam)

data\water.xyz


In [4]:
heylook=numpy.genfromtxt(fname=wherestheleakmaam, skip_header=2, dtype='unicode')
print(heylook)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [6]:
atoms=heylook[:,0]
coords=heylook[:,1:]
bigboicoords=coords.astype(numpy.float)
print(atoms)
print(bigboicoords)

['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [18]:
fuckjerry=len(atoms)
print(fuckjerry)
for start in range(0,fuckjerry):
    for end in range(0,fuckjerry):
        if start<end:
            xdist= bigboicoords[start,0]-bigboicoords[end,0]
            ydist=bigboicoords[start,1]-bigboicoords[end,1]
            zdist=bigboicoords[start,2]-bigboicoords[end,2]
            jamesbondlength=numpy.sqrt(xdist**2+ydist**2+zdist**2)
            if jamesbondlength >0 and jamesbondlength <=1.5:
                print(F'{atoms[start]} to {atoms[end]} : {jamesbondlength:.3f}')

3
O to H1 : 0.969
O to H2 : 0.969
